services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_finance
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_fastify
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/app_finance
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_next
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
    depends_on:
      - backend